"""add epss fields

Revision ID: d9a76d15b758
Revises: 125bc695c0ff
Create Date: 2026-08-28 11:18:28.773899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9a76d15b758'
down_revision: Union[str, Sequence[str], None] = '125bc695c0ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vulnerabilities', sa.Column('epss_score', sa.Float(), nullable=True))
    op.add_column('vulnerabilities', sa.Column('epss_percentile', sa.Float(), nullable=True))
    op.add_column('vulnerabilities', sa.Column('epss_updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vulnerabilities', 'epss_updated_at')
    op.drop_column('vulnerabilities', 'epss_percentile')
    op.drop_column('vulnerabilities', 'epss_score')
    # ### end Alembic commands ###
